/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedListingsIndexRouteImport } from './routes/_authenticated/listings.index'
import { Route as AuthenticatedToolsEnhanceRouteImport } from './routes/_authenticated/tools.enhance'
import { Route as AuthenticatedListingsIdRouteImport } from './routes/_authenticated/listings.$id'
import { Route as AuthenticatedToolsEnhanceIndexRouteImport } from './routes/_authenticated/tools.enhance.index'
import { Route as AuthenticatedToolsEnhanceNewRouteImport } from './routes/_authenticated/tools.enhance.new'
import { Route as AuthenticatedToolsEnhanceIdRouteImport } from './routes/_authenticated/tools.enhance.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListingsIndexRoute =
  AuthenticatedListingsIndexRouteImport.update({
    id: '/listings/',
    path: '/listings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsEnhanceRoute =
  AuthenticatedToolsEnhanceRouteImport.update({
    id: '/tools/enhance',
    path: '/tools/enhance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingsIdRoute = AuthenticatedListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsEnhanceIndexRoute =
  AuthenticatedToolsEnhanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedToolsEnhanceRoute,
  } as any)
const AuthenticatedToolsEnhanceNewRoute =
  AuthenticatedToolsEnhanceNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedToolsEnhanceRoute,
  } as any)
const AuthenticatedToolsEnhanceIdRoute =
  AuthenticatedToolsEnhanceIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedToolsEnhanceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/search': typeof AuthenticatedSearchRoute
  '/listings/$id': typeof AuthenticatedListingsIdRoute
  '/tools/enhance': typeof AuthenticatedToolsEnhanceRouteWithChildren
  '/listings/': typeof AuthenticatedListingsIndexRoute
  '/tools/enhance/$id': typeof AuthenticatedToolsEnhanceIdRoute
  '/tools/enhance/new': typeof AuthenticatedToolsEnhanceNewRoute
  '/tools/enhance/': typeof AuthenticatedToolsEnhanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/search': typeof AuthenticatedSearchRoute
  '/listings/$id': typeof AuthenticatedListingsIdRoute
  '/listings': typeof AuthenticatedListingsIndexRoute
  '/tools/enhance/$id': typeof AuthenticatedToolsEnhanceIdRoute
  '/tools/enhance/new': typeof AuthenticatedToolsEnhanceNewRoute
  '/tools/enhance': typeof AuthenticatedToolsEnhanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/listings/$id': typeof AuthenticatedListingsIdRoute
  '/_authenticated/tools/enhance': typeof AuthenticatedToolsEnhanceRouteWithChildren
  '/_authenticated/listings/': typeof AuthenticatedListingsIndexRoute
  '/_authenticated/tools/enhance/$id': typeof AuthenticatedToolsEnhanceIdRoute
  '/_authenticated/tools/enhance/new': typeof AuthenticatedToolsEnhanceNewRoute
  '/_authenticated/tools/enhance/': typeof AuthenticatedToolsEnhanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/import'
    | '/search'
    | '/listings/$id'
    | '/tools/enhance'
    | '/listings/'
    | '/tools/enhance/$id'
    | '/tools/enhance/new'
    | '/tools/enhance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/import'
    | '/search'
    | '/listings/$id'
    | '/listings'
    | '/tools/enhance/$id'
    | '/tools/enhance/new'
    | '/tools/enhance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/import'
    | '/_authenticated/search'
    | '/_authenticated/listings/$id'
    | '/_authenticated/tools/enhance'
    | '/_authenticated/listings/'
    | '/_authenticated/tools/enhance/$id'
    | '/_authenticated/tools/enhance/new'
    | '/_authenticated/tools/enhance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings/': {
      id: '/_authenticated/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof AuthenticatedListingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/enhance': {
      id: '/_authenticated/tools/enhance'
      path: '/tools/enhance'
      fullPath: '/tools/enhance'
      preLoaderRoute: typeof AuthenticatedToolsEnhanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings/$id': {
      id: '/_authenticated/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof AuthenticatedListingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/enhance/': {
      id: '/_authenticated/tools/enhance/'
      path: '/'
      fullPath: '/tools/enhance/'
      preLoaderRoute: typeof AuthenticatedToolsEnhanceIndexRouteImport
      parentRoute: typeof AuthenticatedToolsEnhanceRoute
    }
    '/_authenticated/tools/enhance/new': {
      id: '/_authenticated/tools/enhance/new'
      path: '/new'
      fullPath: '/tools/enhance/new'
      preLoaderRoute: typeof AuthenticatedToolsEnhanceNewRouteImport
      parentRoute: typeof AuthenticatedToolsEnhanceRoute
    }
    '/_authenticated/tools/enhance/$id': {
      id: '/_authenticated/tools/enhance/$id'
      path: '/$id'
      fullPath: '/tools/enhance/$id'
      preLoaderRoute: typeof AuthenticatedToolsEnhanceIdRouteImport
      parentRoute: typeof AuthenticatedToolsEnhanceRoute
    }
  }
}

interface AuthenticatedToolsEnhanceRouteChildren {
  AuthenticatedToolsEnhanceIdRoute: typeof AuthenticatedToolsEnhanceIdRoute
  AuthenticatedToolsEnhanceNewRoute: typeof AuthenticatedToolsEnhanceNewRoute
  AuthenticatedToolsEnhanceIndexRoute: typeof AuthenticatedToolsEnhanceIndexRoute
}

const AuthenticatedToolsEnhanceRouteChildren: AuthenticatedToolsEnhanceRouteChildren =
  {
    AuthenticatedToolsEnhanceIdRoute: AuthenticatedToolsEnhanceIdRoute,
    AuthenticatedToolsEnhanceNewRoute: AuthenticatedToolsEnhanceNewRoute,
    AuthenticatedToolsEnhanceIndexRoute: AuthenticatedToolsEnhanceIndexRoute,
  }

const AuthenticatedToolsEnhanceRouteWithChildren =
  AuthenticatedToolsEnhanceRoute._addFileChildren(
    AuthenticatedToolsEnhanceRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedListingsIdRoute: typeof AuthenticatedListingsIdRoute
  AuthenticatedToolsEnhanceRoute: typeof AuthenticatedToolsEnhanceRouteWithChildren
  AuthenticatedListingsIndexRoute: typeof AuthenticatedListingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedListingsIdRoute: AuthenticatedListingsIdRoute,
  AuthenticatedToolsEnhanceRoute: AuthenticatedToolsEnhanceRouteWithChildren,
  AuthenticatedListingsIndexRoute: AuthenticatedListingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
